GET http://localhost:5000/doctor
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiZG9jdG9yIiwic3ViIjoiZGFtb24iLCJpYXQiOjE3NTk5NDU1MjEsImV4cCI6MTc2MDAzMTkyMX0.cIwf4aAMy4YceTVvvqdQXtlux0_IUPwHDkFYscylWy0

# {
#     "fullName": "Avinash Yennam",
#      "specialty": "Neuro Surgeon",
#   "contactNumber": "9876543212",
#   "email": "yennam@gmail.com",
#   "yearsOfExperience": 6
# }

# POST http://localhost:5000/users/login
# Content-Type: application/json

# {
#     "username": "damon",
#     "password": "damon123"
# }

# {
#     "username": "damon",
#     "password": "damon123",
#      "role": "doctor",
#      "fullName": "Damon Salvatour",
#      "contactNumber": "9876543212",
#      "email": "damon@gmail.com",
#      "address": "Mystic falls",
#      "dateOfBirth": "23-10-2001",
#      "specialty": "Surgeon",
#      "yearsOfExperience": 5
# }

# {
#     "fullName": "Bishnu raut",
#     "dateOfBirth": "23-10-2001",
#     "contactNumber": "9876543212",
#     "email": "bishnu@gmail.com",
#     "address": "puri"
# }

# {
#     "username": "Bishnu",
#     "password": "b@1234"
# }

    # "role": "patient",
    # "fullName": "Bishnu raut",
    # "contactNumber": "9876543212",
    # "email": "bishnu@gmail.com",
    # "address": "puri",
    # "dateOfBirth": "23-10-2001",
    # "specialty": "Surgeon",
    # "yearsOfExperience": 5