# POST http://localhost:5000/user/login
# Content-Type: application/json

# {
#     "username": "doctor",
#     "password": "Doctor@123"
# }

GET http://localhost:5000/clinic/doctor/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiRE9DVE9SIiwic3ViIjoiZG9jdG9yIiwiaWF0IjoxNzYxMTUwNjI4LCJleHAiOjE3NjEyMzcwMjh9.OwpGNLFHCr1bVoJETPPTTeXXZLgdM4jC8MNCVPrzNB8

# {
#     "clinicId": 15,
#   "clinicName": "Vasudeva Hospital",
#   "location": "vemulawada",
#   "contactNumber": "9876543211",
#   "establishedYear": 2017,
#   "doctorId": 1
# }

# "doctorId": 5,
# {
#     "patientId": 1,
#     "fullName": "Lti mindtree",
#     "dateOfBirth": "17-04-2019",
#     "contactNumber": "7607071130",
#     "email": "sample798@gmail.com",
#     "address": "odisha"
#   }

# {
#     "fullName": "Gautam verma",
#     "specialty": "Surgeon",
#     "contactNumber": "7607071130",
#     "email": "developergautam41@gmail.com",
#     "yearsOfExperience": 2
#   }

# GET http://localhost:5000/doctor
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiZG9jdG9yIiwic3ViIjoiZGFtb24iLCJpYXQiOjE3NTk5NDU1MjEsImV4cCI6MTc2MDAzMTkyMX0.cIwf4aAMy4YceTVvvqdQXtlux0_IUPwHDkFYscylWy0

# {
#     "fullName": "Avinash Yennam",
#      "specialty": "Neuro Surgeon",
#   "contactNumber": "9876543212",
#   "email": "yennam@gmail.com",
#   "yearsOfExperience": 6
# }



# POST http://localhost:5000/user/register
# Content-Type: application/json

# {
#     "username": "damon",
#     "password": "damon123",
#      "role": "doctor",
#      "fullName": "Damon Salvatour",
#      "contactNumber": "9876543212",
#      "email": "damon@gmail.com",
#      "address": "Mystic falls",
#      "dateOfBirth": "23-10-2001",
#      "specialty": "Surgeon",
#      "yearsOfExperience": 5
# }

# {
#     "fullName": "Bishnu raut",
#     "dateOfBirth": "23-10-2001",
#     "contactNumber": "9876543212",
#     "email": "bishnu@gmail.com",
#     "address": "puri"
# }


    # "role": "patient",
    # "fullName": "Bishnu raut",
    # "contactNumber": "9876543212",
    # "email": "bishnu@gmail.com",
    # "address": "puri",
    # "dateOfBirth": "23-10-2001",
    # "specialty": "Surgeon",
    # "yearsOfExperience": 5